### ISSUE TITLE
beginner problems...

### ISSUE THREAD

**Issue by whcrg** [Chostakovitch/pychee#3]
Hello

This seems to be what I need, I am trying to automate importing large contunously expandin photo collection to Lychee and Lychees native cli-import does not offer fine grained enough control.

Unfortunately I am total beginner in python and have hard time getting up to speed with pychee. 

Could you provide couple of basic examples: how to create new album "X" for user 0, how to import photo to album X

Also a question: can pychee import a photo by symlink, its not very clear to me even after reading through https://github.com/Chostakovitch/pychee/blob/main/pychee/pychee.py

**Comment by Chostakovitch** [comment]
@whcrg What do you mean by "import a photo by symlink" ?

Also, you're right, the README lacks examples... I'll add a few.

**Comment by Chostakovitch** [comment]
Hey, please see [there](https://github.com/Chostakovitch/pychee/blob/main/README.md#example-usage) for an example to create an album and upload a photo to it, among other things.

Be sure to upgrade your `pychee` installation :

```
pip install --upgrade pychee
```

**Comment by whcrg** [comment]
by "import a photo by symlink" I mean adding photos to gallery in similar fashion that can be achieved with Lychee command line tool `php artisan lychee:sync ./picfoder --import_via_symlink=1` but for one single picture (the lychee native tool does not take singel file, only folder)

Will take a look at example!

**Comment by Chostakovitch** [comment]
Hey @whcrg. From what I understand, importing via symlink avoid copying the file and simply uses the file in-place. 

`pychee` is a client for the API (*i.e.* acts "as your web browser"), and importing via symlink cannot be done through the API, which requires a file to be uploaded.  

If you're not totally sure about whether the tool is suited for you, please ask and we can have a look.

**Comment by Chostakovitch** [comment]
Closing as no answers.
