### ISSUE TITLE
KeyError: "name='XSRF-TOKEN', domain=None, path=None"

### ISSUE THREAD

**Issue by Glokeru** [Chostakovitch/pychee#4]
First of all thanks for this Library. I want to do a sync script which syncs folders in an album with the same name. The easiest ways seems to be pychee. I tried the sample code first and got this error. 

`Traceback (most recent call last):
  File "sync_folder.py", line 6, in <module>
    client = pychee.LycheeClient('https://foto.hans2.de')
  File "/home/hans/.local/lib/python3.8/site-packages/pychee/pychee.py", line 69, in __init__
    csrf_token = unquote(init_response.cookies['XSRF-TOKEN'])
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='XSRF-TOKEN', domain=None, path=None"
`

Any idea what causes this? My Lychee version is 4.5.1. 

Thanks!

**Comment by Chostakovitch** [comment]
Hey @Glokeru, I know it's been a while but I just have not been notified for that issue.

Lychee changed a few things breaking the package. I released a [new version](https://github.com/Chostakovitch/pychee/releases/tag/v0.2.0) if you still need it.

More work is needed to make this package a bit more robust, but right now it works with the latest version (3.7.0).
